# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sad slut club
description: > # this means to ignore newlines until "baseurl:"
  HOME OF THE THOTS
repository: https://github.com/pantywitch/pantywitch.github.io
baseurl: / # the subpath of your site, e.g. /blog
url: https://pantywitch.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: selkie
email: selkie@sadslut.club

navigation:
  - text: home
    url: /
  - text: blog # Miscellaneous posts and updates, also shows all writing, art, and ttrpg posts mixed together like I was raised in a barn
    url: /blog
  - text: ttrpgs
    url: /ttrpgs
  - text: art
    url: /art
  - text: writing
    url: /writing
  - text: misc projects # Other gamedev and whatever other shit
    url: /misc

# Collections
collections_dir: collections
collections:
  - art
  - projects
  - social
  - ttrpg_posts
  - ttrpg_projects
  - writing

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji

# If using another social media website other than github
#jekyll-mentions:
  #base_url: https://twitter.com
