# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sad slut club
description: > # this means to ignore newlines until "baseurl:"
  HOME OF THE THOTS
repository: https://github.com/pantywitch/pantywitch.github.io
baseurl: / # the subpath of your site, e.g. /blog
url: https://pantywitch.github.io  # the base hostname & protocol for your site
encoding: UTF-8 # force UTF-8

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Selkie
email: selkie@sadslut.club

# Tabletop Projects
ttrpg_projects:
  - name: test
    description: very cool test
    link: https://www.google.com/
    image: https://github.com/pantywitch/files/blob/master/icons/him.png?raw=true

# Misc Projects
projects:
  - name: monster girl maker
    description: an oldish pixel-art monster girl dress up game with limited options. circa 2016 or 2017
    category: projects
    link: https://selkie.itch.io/monster-girl-maker
    image: https://github.com/pantywitch/files/blob/master/project%20covers/monstergirlmakercover.png?raw=true

navigation:
  - text: home
    url: /
  - text: blog # Miscellaneous posts and updates, also shows all writing, art, and ttrpg posts mixed together like I was raised in a barn
    url: /blog
  - text: art
    url: /art
  - text: writing
    url: /writing
  - text: misc projects # Other gamedev and whatever other shit
    url: /misc

social:
  - service: twitter
    username: pantywitch
    link: https://twitter.com/pantywitch
  - service: instagram
    username: pantywitchcraft
    link: https://instagram.com/pantywitchcraft
  - service: patreon
    username: pantywitch
    link: https://patreon.com/pantywitch

# Collections
collections_dir: collections
collections:
  - art
  - ttrpgs
  - writing

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" #
    values:
      image_preview: "https://github.com/pantywitch/files/blob/master/icons/him.png?raw=true"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji

#Commentbox.io
commentbox:
 id: 5696039231160320-proj
 subtextColor: "#FF2687"

# If using another social media website other than github
#jekyll-mentions:
  #base_url: https://twitter.com
